name: CI
on:
  push:
    branches: [ main ]

jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Print hello actions
        run: echo "Hello GithubActions"
        
  test:
    runs-on: [windows, ubuntu-latest]
    steps:
      - name: Test1
        run: echo "Run on windows and ubuntu"
