name: CI
env:
  APP: "ihs"
on:
  push:
    branches: [ main ]

jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Print hello actions
        run: ls -la
        
  test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Test1
        run: echo "Run on windows and ubuntu"
        
      - name: Clone repo
        uses: actions/checkout@v1
      
      - name: List files
        run: ls -la
