name: CI
env:
  APP: "ihs"
on:
  push:
    branches: [ main ]

jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Print hello actions
        run: |
          echo "Hello GithubActions"
          echo "APP: ${{ env.APP }}"
          echo "$LOCAL_ENV"
        env:
          LOCAL_ENV: "LOCAL ENV"
        
  test:
    runs-on: windows-latest
    needs: [build]
    steps:
      - name: Test1
        run: echo "Run on windows and ubuntu"
